export interface LanguageOption {
  value: string;
  label: string;
}

export const programmingLanguages: LanguageOption[] = [
  { value: 'Assembly', label: 'Assembly' },
  { value: 'Bash', label: 'Bash' },
  { value: 'Batch', label: 'Batch' },
  { value: 'C', label: 'C' },
  { value: 'CPlusPlus', label: 'C++' },
  { value: 'CSharp', label: 'C#' },
  { value: 'CSS', label: 'CSS' },
  { value: 'Clojure', label: 'Clojure' },
  { value: 'COBOL', label: 'COBOL' },
  { value: 'Dart', label: 'Dart' },
  { value: 'Elixir', label: 'Elixir' },
  { value: 'Erlang', label: 'Erlang' },
  { value: 'FSharp', label: 'F#' },
  { value: 'Fortran', label: 'Fortran' },
  { value: 'Go', label: 'Go' },
  { value: 'Groovy', label: 'Groovy' },
  { value: 'Haskell', label: 'Haskell' },
  { value: 'HTML', label: 'HTML' },
  { value: 'Java', label: 'Java' },
  { value: 'JavaScript', label: 'JavaScript' },
  { value: 'JSON', label: 'JSON' },
  { value: 'Julia', label: 'Julia' },
  { value: 'Kotlin', label: 'Kotlin' },
  { value: 'Lua', label: 'Lua' },
  { value: 'Markdown', label: 'Markdown' },
  { value: 'MATLAB', label: 'MATLAB' },
  { value: 'OCaml', label: 'OCaml' },
  { value: 'ObjectiveC', label: 'Objective-C' },
  { value: 'Other', label: 'Other' },
  { value: 'Perl', label: 'Perl' },
  { value: 'PHP', label: 'PHP' },
  { value: 'PLSQL', label: 'PL/SQL' },
  { value: 'PowerShell', label: 'PowerShell' },
  { value: 'Python', label: 'Python' },
  { value: 'R', label: 'R' },
  { value: 'Ruby', label: 'Ruby' },
  { value: 'Rust', label: 'Rust' },
  { value: 'Scala', label: 'Scala' },
  { value: 'Solidity', label: 'Solidity' },
  { value: 'SQL', label: 'SQL' },
  { value: 'Swift', label: 'Swift' },
  { value: 'TOML', label: 'TOML' },
  { value: 'TSQL', label: 'T-SQL' },
  { value: 'TypeScript', label: 'TypeScript' },
  { value: 'VBA', label: 'VBA' },
  { value: 'Verilog', label: 'Verilog' },
  { value: 'VHDL', label: 'VHDL' },
  { value: 'XML', label: 'XML' },
  { value: 'YAML', label: 'YAML' },
  { value: 'Zig', label: 'Zig' },
  { value: 'Zsh', label: 'Zsh' },
].sort((a, b) => a.label.localeCompare(b.label));
